export const iconTypes = {
    bug: "/fonts/types/Bug_icon_SwSh.png",
    dark: "/fonts/types/Dark_icon_SwSh.png",
    dragon: "/fonts/types/Dragon_icon_SwSh.png",
    electric: "/fonts/types/Electric_icon_SwSh.png",
    fighting: "/fonts/types/Fighting_icon_SwSh.png",
    fire: "/fonts/types/Fire_icon_SwSh.png",
    flying: "/fonts/types/Flying_icon_SwSh.png",
    ghost: "/fonts/types/Ghost_icon_SwSh.png",
    grass: "/fonts/types/Grass_icon_SwSh.png",
    ground: "/fonts/types/Ground_icon_SwSh.png",
    ice: "/fonts/types/Ice_icon_SwSh.png",
    normal: "/fonts/types/Normal_icon_SwSh.png",
    poison: "/fonts/types/Poison_icon_SwSh.png",
    psychic: "/fonts/types/Psychic_icon_SwSh.png",
    rock: "/fonts/types/Rock_icon_SwSh.png",
    steel: "/fonts/types/Steel_icon_SwSh.png",
    water: "/fonts/types/Water_icon_SwSh.png",
}